sudo: required

language: go

go:
  - 1.17.x

go_import_path: github.com/bosh-prometheus/bosh_exporter

services:
  - docker

jobs:
  include:
    - stage: Run tests
      script: make test

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=boshprometheus/bosh-exporter
        - secure: QFgM4fwAmQsB+3rIK0oo7jh0QulRgBOYXFTqjorHtF7vJc3aNAtev+Ep4u2OmSpIInJyIQKyLDbowuwsvqcIglVI52UGTRpULDrvdm5doVN88IMXL6mG3E5ZCZ+xmj1N9Vq7BDUuemH4n4fR5nm9ZY8xeCxg1lR2/dhMDR8uhxUnjmkUoAY+1l+rNTFsqBoOWH0q55ibdb0vQcmF8+jBkflXgbJfqiQO32mw5nuFkhtpVUyR1voC2w7RonCr0IfpL0vIzIA/MNJMw5dwA7W1d6Ot6zQR8K6mPIjDu3TaP8kIUNdhswVgqPszA0IkDRVL5mg8HiOW508v3uoS5inua/mpSwu1TH3v/H/XX3Tm9jum9YZk37KS5kVy6+T8tzebavP2hdeXmewXltGceexGUUN7j9EuFVauyX+8HktwK+VjkeFrliHSk8Jrg194ynD2cerqVawbCXbZN7z9Er4PJjh+kYBHY4XmAHJparQ07Fd0wk799zByQ0QwRUAxojvei09XVVyJSNajd9BJ97f2oS3ZN5rZKrJ89OoqA41tBaXSyqrk8oSsbE68MUmuTSk6/vnG8cPzM/d9f8BxWFdKrGvWlP0WaRQpt/VKeDfw9AAvYt56p/8Dsg4sLTzNfgwSqwYXkPuez6dmAAJgpipS7kZiAJHVrCprxksRn2qeg/Q=
        - secure: hydxR7bjxOwb1kU0QfM7Xm2GOjXa9X9lxazqJk+T+QLOBC0d1zHSmcMPI7KSzqXYEJbdi15EuwhGUMfeDuKbZX06q2NuLKMGcTpuK1qIQpfevMfkUg+PkuaPRmFj+RvI34o/KLTbFdZ5mVovfEj4sPmPV2NCsOAqWEntCbn/Ee3sQUZsdSX+EWHg/jPjKKgzTOBZt3Zcj14soUv/l1lnuk0nl0jB9QQbkv3St4RdnPyv5G35uZMXW3fnu04lYBR15PS/sDKD5dO65ocSU71IltwIH5LdSZIoSEePImeAOkV8+x7Q46vfLF4xVIGUj08bGnUlCuWKUki+gxp2Il2aq5JZH7X9uLLtA+x0EhMAq9GhBLd/kNFbwkaIKUkaL8CeQMo4BsdjG0a7BIV+JcVQgB08Sga0AE9V25KA69kG6dvrOdV4Hsz1J0XUzEydjy7+SKlqfK3IsSE4kESJznGiNszxpHj0g6Nf5qktjWEpCHkcy43DllHjQSJhOPFcULCV08YRyVEFtqRoQ+voKNnPXEYDSiAXDA0tbB2qznj4aG3VXO4SdKj/FwIdqLAHOREtTU1IIS/7BU55BfpI7MlOUM8SJVhPP2W3qbBnyOB0DEwBwx/v2N7Eui8sMg/1TKTS9vOyinEc1cuWCvZcRbfgmRWWZkmrpTtsY5ATYQm0ROg=
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_exporter bosh_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
